import type { Vehicle } from '@/types/vehicle';

export const mockVehicles: Vehicle[] = [
  {
    id: 167,
    title: '300 Touring',
    brand: 'Chrysler',
    price: 28999.99,
    rating: 4.05,
    description: 'Stylish and comfortable sedan',
    category: 'vehicle',
    stock: 54,
    tags: ['sedans', 'vehicles'],
    sku: 'VEH-CHR-TOU-167',
    weight: 9,
    dimensions: { width: 19.2, height: 26.17, depth: 17.28 },
    warrantyInformation: '3 year warranty',
    shippingInformation: 'Ships in 2 weeks',
    availabilityStatus: 'In Stock',
    returnPolicy: '30 days return policy',
    images: ['https://cdn.dummyjson.com/product-images/vehicle/300-touring/1.webp'],
    thumbnail:
      'https://cdn.dummyjson.com/product-images/vehicle/300-touring/thumbnail.webp',
    reviews: [
      {
        rating: 4,
        comment: 'Very pleased!',
        date: '2025-04-30T09:41:02.054Z',
        reviewerName: 'Luna Russell',
        reviewerEmail: 'luna.russell@x.dummyjson.com',
      },
    ],
  },
  {
    id: 168,
    title: 'Charger SXT RWD',
    brand: 'Dodge',
    price: 32999.99,
    rating: 2.58,
    description: 'Powerful and sporty sedan',
    category: 'vehicle',
    stock: 57,
    tags: ['sedans', 'sports cars'],
    sku: 'VEH-DOD-CHA-168',
    weight: 6,
    dimensions: { width: 16.77, height: 23.03, depth: 8.18 },
    warrantyInformation: '1 month warranty',
    shippingInformation: 'Ships in 3-5 business days',
    availabilityStatus: 'In Stock',
    returnPolicy: 'No return policy',
    images: [
      'https://cdn.dummyjson.com/product-images/vehicle/charger-sxt-rwd/1.webp',
    ],
    thumbnail:
      'https://cdn.dummyjson.com/product-images/vehicle/charger-sxt-rwd/thumbnail.webp',
    reviews: [],
  },
  {
    id: 170,
    title: 'Durango SXT RWD',
    brand: 'Dodge',
    price: 36999.99,
    rating: 4.07,
    description: 'Spacious and versatile SUV',
    category: 'vehicle',
    stock: 95,
    tags: ['suvs', 'vehicles'],
    sku: 'VEH-DOD-DUR-170',
    weight: 1,
    dimensions: { width: 19.02, height: 29.52, depth: 24.36 },
    warrantyInformation: '2 year warranty',
    shippingInformation: 'Ships in 1 month',
    availabilityStatus: 'In Stock',
    returnPolicy: '30 days return policy',
    images: [
      'https://cdn.dummyjson.com/product-images/vehicle/durango-sxt-rwd/1.webp',
    ],
    thumbnail:
      'https://cdn.dummyjson.com/product-images/vehicle/durango-sxt-rwd/thumbnail.webp',
    reviews: [
      {
        rating: 5,
        comment: 'Great value!',
        date: '2025-04-30T09:41:02.054Z',
        reviewerName: 'David Martinez',
        reviewerEmail: 'david.martinez@x.dummyjson.com',
      },
    ],
  },
];
